init:
  - git config --global core.autocrlf input

build: off
version: '{build}'
shallow_clone: true
clone_depth: 1

environment:
  matrix:
    - nodejs_version: '1' # iojs
    - nodejs_version: '0.12'
    - nodejs_version: '0.10'

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - npm test
